FROM almalinux:9
# CMD["ping", "google.com"]
# This Dockerfile demonstrates the use of ENTRYPOINT and CMD instructions.
# The ENTRYPOINT instruction sets the default command to be executed when the container starts,
CMD ["google.com"]
ENTRYPOINT [ "ping" ] 